services:
  app:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/myproject/staticfiles
      - media_volume:/app/myproject/media
      - db_volume:/app/myproject  
    environment:
      - PYTHONUNBUFFERED=1
    expose:
      - "8000"
    restart: unless-stopped  
    deploy:
      resources:
        limits:
          memory: 6g 

  nginx:
    image: nginx:1.24  
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs:ro
      - static_volume:/app/myproject/staticfiles
      - media_volume:/app/myproject/media
    depends_on:
      - app
    restart: unless-stopped  
    deploy:
      resources:
        limits:
          memory: 6g  

volumes:
  static_volume:
  media_volume:
  db_volume:
