# Generated by Django 5.1.7 on 2025-03-25 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'permissions': [('view_section1', 'Can view section 1 surveys'), ('view_section2', 'Can view section 2 surveys'), ('view_section3', 'Can view section 3 surveys')]},
        ),
    ]
