# Generated by Django 5.1.7 on 2025-03-25 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_alter_survey_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'permissions': [('view_section1', 'Can view section 1 surveys'), ('view_section2', 'Can view section 2 surveys'), ('view_section3', 'Can view section 3 surveys')], 'verbose_name': 'نظرسنجی', 'verbose_name_plural': 'نظرسنجی\u200cها'},
        ),
        migrations.AddField(
            model_name='survey',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_surveys', to=settings.AUTH_USER_MODEL, verbose_name='کاربران مجاز'),
        ),
    ]
