# Generated by Django 5.1.7 on 2025-03-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_survey_options_survey_assigned_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'verbose_name': 'پاسخ', 'verbose_name_plural': 'پاسخ\u200cها'},
        ),
        migrations.AddField(
            model_name='response',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی'),
        ),
    ]
