# Generated by Django 5.1.7 on 2025-03-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_alter_response_options_response_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'پاسخ متنی'), ('single', 'تک انتخابی'), ('multiple', 'چند انتخابی')], max_length=20),
        ),
    ]
