# Generated by Django 5.1.7 on 2025-03-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'permissions': [('view_section1', 'Can view section 1 surveys'), ('view_section2', 'Can view section 2 surveys')], 'verbose_name': 'نظرسنجی', 'verbose_name_plural': 'نظرسنجی\u200cها'},
        ),
        migrations.AlterField(
            model_name='survey',
            name='section',
            field=models.CharField(choices=[('section1', 'بخش اول'), ('section2', 'بخش دوم')], max_length=20),
        ),
    ]
