# Generated by Django 5.1.7 on 2025-03-25 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_alter_survey_options_alter_survey_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['subsection__order', 'order']},
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان زیربخش')),
                ('order', models.IntegerField(verbose_name='ترتیب')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='surveys.survey')),
            ],
            options={
                'verbose_name': 'زیربخش',
                'verbose_name_plural': 'زیربخش\u200cها',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='subsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.subsection'),
        ),
    ]
