# Generated by Django 5.1.7 on 2025-03-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_alter_question_options_subsection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsection',
            name='title',
            field=models.CharField(choices=[('medical_center', 'مشخصات مرکز درمانی'), ('hospital_management', 'پایش مدیریتی بیمارستان'), ('emergency', 'پایش بخش اورژانس'), ('paraclinic', 'پایش بخش پاراکلینیک،بستری سرپایی'), ('other', 'غیره')], max_length=200, verbose_name='عنوان زیربخش'),
        ),
    ]
